version: '3.8'

services:
  mssql:
    networks:
      default_net:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: root@@@123  
      ACCEPT_EULA: Y
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"

  mysql:
    networks:
      default_net:
    image: mysql:9.0
    # command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      server-id: 123
      server_id: 123
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--password=root"]
      interval: 1s
      timeout: 20s
      retries: 5
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/my.cnf
    restart: always    

volumes:
  mssql_data:  
   
networks:
  default_net:
    external: true