version: '3.8'

x-service-common:
  &service-common
  deploy:
    resources:
      reservations:
        memory: 1G
      limits:
        memory: 1G

services:
  mssql:
    <<: *service-common
    networks:
      default_net:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: root@@@123  
      ACCEPT_EULA: Y
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"

  mysql:
    <<: *service-common
    networks:
      default_net:
    image: mysql:9.0
    # command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      server-id: 123
      server_id: 123
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--password=root"]
      interval: 1s
      timeout: 20s
      retries: 5
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/my.cnf
    restart: always    

  nginx:
    <<: *service-common
    image: nginx:1.27.2
    container_name: nginx
    networks:
      default_net:
    hostname: nginx
    volumes:
    # - ./templates:/etc/nginx/templates
      - ./nginx_logs:/var/log/nginx
    ports:
    - "8183:80"
    environment:
    # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    restart: always    
  
  logstash:
    <<: *service-common
    networks:
      default_net:
    image: logstash:8.15.3
    ports:
      - "8342:8090"
    container_name: logstash
    hostname: logstashs
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./conf/logstash_pipeline/nginx_http.conf:/usr/share/logstash/pipeline/nginx_http.conf
    restart: always    

volumes:
  mssql_data:  
   
networks:
  default_net:
    external: true