# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'lakehouse_dev'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'lakehouse_dev'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]



clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  # dbt_data_lakehouse_query:
    # +schema: "{{ target.schema }}"
    # +post-hook:
    #   - "{{ run_expire_snapshots_with_dynamic_date(this) }}"
    #   - "{{ run_remove_orphan_files_with_dynamic_date(this) }}"
    #   - "{{ rewrite_manifests(this) }}"
      
  dbt_data_lakehouse_query:
    +schema: 'bi_retail_warehouse'
    sale_report:
      +materialized: table
      +file_format: iceberg
      # +location_root: '/test/lv1'
      +incremental_strategy: insert_overwrite

          

vars:
  dbt_date:time_zone: 'UTC+7'
