version: "3.8"

services:
  superset:
    deploy:
      resources:
        reservations:
          memory: 1G # Set memory reservation (minimum guaranteed)
        limits:
          memory: 1G
    build: .
    container_name: superset
    restart: unless-stopped
    network_mode: host
    environment:
      SUPERSET_SECRET_KEY: your_secret_key_here 
    volumes:
      - superset_home:/app/superset_home
      
volumes:
  superset_home: